root: true
env:
  browser: true
  es2021: true
  "vue/setup-compiler-macros": true
parser: "vue-eslint-parser"
parserOptions:
  parser: "@typescript-eslint/parser"
  sourceType: module
extends:
  - "eslint:recommended"
  - "plugin:vue/vue3-essential"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
plugins:
  - "vue"